import itertools as it
import time
import random

def gen_comb(a_n):
    st = list(range(1,a_n+1))


    diffs = []
    while len(diffs)<0
        for i in range(a_n):
            subsample = sorted(random.sample(range(1, a_n), i))
            if 
            diffs.append(subsample)
     

    return diffs
   



s = time.time()
test1 = gen_comb(7)
e = time.time()
d = e - s
print(d)

#operations(-,+,**,) between next current
#generated by
#   range constraint
#   unfiltered possible variations
#
